version: '3.2'
services:
  node-server:
    image: node:10
    container_name: node-server.facebook-flexbox.com
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "80:3000"
    command: bash -c 'yarn start'